-- ============================================================================
-- 01_schema.sql  -  Tablas base (SAMPLE: sample_shop)
--
-- Contrato: aqui van SOLO las tablas y sus columnas. Los PK/FK/indices van en
-- 02_constraints_indexes.sql. El toolkit descubre PK y tipos por introspeccion
-- del information_schema, no del texto de este archivo.
--
-- Las columnas identity son GENERATED BY DEFAULT AS IDENTITY: aceptan el INSERT
-- explicito del PK original (asi la migracion preserva los IDs 1:1) y luego
-- reset_sequences() deja cada secuencia en MAX(pk).
--
-- Los tipos elegidos ejercitan a proposito cada chequeo de --validate:
--   * integer / numeric        -> suma EXACTA comparada origen vs destino
--   * double precision         -> EXCLUIDA de sumas (aproximada, no comparable)
--   * varchar / text           -> paridad de strings fila a fila
--   * uuid como PK (ApiToken)  -> fuerza la estrategia "match por dict"
--   * boolean / timestamptz / jsonb -> se copian intactos (no se suman)
-- ============================================================================

-- Categorias de producto -----------------------------------------------------
CREATE TABLE "Category" (
    "IdCategory"  integer      GENERATED BY DEFAULT AS IDENTITY,
    "Name"        varchar(100) NOT NULL,
    "Description" text
);

-- Productos ------------------------------------------------------------------
CREATE TABLE "Product" (
    "IdProduct"   integer        GENERATED BY DEFAULT AS IDENTITY,
    "IdCategory"  integer        NOT NULL,
    "Sku"         varchar(40)    NOT NULL,
    "Name"        varchar(200)   NOT NULL,
    "Description" text,
    "Price"       numeric(12,2)  NOT NULL,   -- suma exacta
    "Weight"      double precision,          -- EXCLUIDA de sumas (aproximada)
    "InStock"     boolean        NOT NULL DEFAULT true,
    "StockQty"    integer        NOT NULL DEFAULT 0,  -- suma exacta
    "Attributes"  jsonb,                     -- blob JSON: round-trip por COPY
    "CreatedAt"   timestamptz    NOT NULL DEFAULT now()
);

-- Clientes -------------------------------------------------------------------
CREATE TABLE "Customer" (
    "IdCustomer"  integer      GENERATED BY DEFAULT AS IDENTITY,
    "FullName"    varchar(150) NOT NULL,
    "Email"       varchar(255) NOT NULL,   -- colacion CI/AS aplicada en 02
    "IsActive"    boolean      NOT NULL DEFAULT true,
    "CreatedAt"   timestamptz  NOT NULL DEFAULT now()
);

-- Pedidos --------------------------------------------------------------------
CREATE TABLE "Order" (
    "IdOrder"     integer        GENERATED BY DEFAULT AS IDENTITY,
    "IdCustomer"  integer        NOT NULL,
    "OrderDate"   timestamptz    NOT NULL DEFAULT now(),
    "Total"       numeric(12,2)  NOT NULL DEFAULT 0,   -- suma exacta
    "Notes"       text
);

-- Lineas de pedido -----------------------------------------------------------
CREATE TABLE "OrderLine" (
    "IdOrderLine" integer        GENERATED BY DEFAULT AS IDENTITY,
    "IdOrder"     integer        NOT NULL,
    "IdProduct"   integer        NOT NULL,
    "Quantity"    integer        NOT NULL,             -- suma exacta
    "UnitPrice"   numeric(12,2)  NOT NULL,             -- suma exacta
    "Discount"    double precision NOT NULL DEFAULT 0  -- EXCLUIDA (aproximada)
);

-- Tokens de API: PK uuid a proposito, para demostrar el "match por dict" de la
-- paridad de strings (un uuid ordena distinto en cada motor, no sirve keyset).
CREATE TABLE "ApiToken" (
    "Id"          uuid         NOT NULL DEFAULT gen_random_uuid(),
    "IdCustomer"  integer      NOT NULL,
    "Token"       varchar(64)  NOT NULL,   -- paridad de strings con PK uuid
    "ExpiresAt"   timestamptz  NOT NULL,
    "Revoked"     boolean      NOT NULL DEFAULT false
);
