"""etl.py - Copia de DATOS MS SQL Server -> PostgreSQL (100% Python).

Copia Geus_ISP_DB tabla por tabla PRESERVANDO los PK con su valor exacto (las
columnas destino son GENERATED BY DEFAULT AS IDENTITY, aceptan insert explicito).
Es SCHEMA-DRIVEN: descubre las tablas base y sus columnas del esquema PostgreSQL
destino (information_schema), no hardcodea las 57 tablas. Las 24 VISTAS quedan
fuera (una vista no tiene datos; se recrean por DDL).

Ventaja frente a bcp/CSV: psycopg maneja el escaping del protocolo COPY
internamente, asi que el texto libre con comas/comillas/saltos de linea y los
blobs JSON (JsonParameters, Query) viajan intactos. Y al conectarse directo a
ambos motores (pyodbc + psycopg), no depende de la red de contenedores.

Durante la carga deshabilita las FK en su propia sesion
(session_replication_role=replica, requiere superusuario) para poder cargar en
cualquier orden. Al final re-sincroniza las secuencias identity con reset_sequences()
(tambien via psycopg: sin psql).

(Archivo en ASCII puro a proposito.)
"""
from __future__ import annotations

from . import config


# ------------------------------------------------------------- introspeccion PG
def pg_base_tables(pg):
    cur = pg.execute(
        "SELECT table_name FROM information_schema.tables "
        "WHERE table_schema='public' AND table_type='BASE TABLE' ORDER BY table_name")
    return [r[0] for r in cur.fetchall()]


def pg_columns(pg, table):
    cur = pg.execute(
        "SELECT column_name FROM information_schema.columns "
        "WHERE table_schema='public' AND table_name=%s ORDER BY ordinal_position",
        (table,))
    return [r[0] for r in cur.fetchall()]


def truncate_all(pg, tables):
    if not tables:
        return
    lst = ", ".join(config.qi(t) for t in tables)
    pg.execute("TRUNCATE %s RESTART IDENTITY CASCADE" % lst)


# ----------------------------------------------------------------------- copia
def stream_mssql(mssql, table, columns, batch):
    """Genera tuplas leyendo del ORIGEN MSSQL en lotes (memoria acotada)."""
    srccols = ", ".join("[%s]" % c for c in columns)
    cur = mssql.cursor()
    cur.execute("SELECT %s FROM [dbo].[%s]" % (srccols, table))
    while True:
        rows = cur.fetchmany(batch)
        if not rows:
            break
        for r in rows:
            yield tuple(r)


def copy_into_pg(pg, table, columns, rows):
    """COPY de un iterable de tuplas al destino PG. Devuelve nro de filas.
    psycopg adapta cada valor Python al formato COPY (con escaping correcto)."""
    collist = ", ".join(config.qi(c) for c in columns)
    sql = "COPY %s (%s) FROM STDIN" % (config.qi(table), collist)
    n = 0
    with pg.cursor() as cur:
        with cur.copy(sql) as cp:
            for row in rows:
                cp.write_row(row)
                n += 1
    return n


def reset_sequences(pg):
    """Re-sincroniza cada secuencia identity a MAX(pk). 100% Python (sin psql).

    La carga inserta los PK con su valor explicito, pero la secuencia interna no
    avanza sola; sin esto, el primer INSERT nuevo de la app colisionaria con un PK
    migrado. Deja cada secuencia en MAX(pk) -> siguiente id = MAX+1 (o 1 si vacia).
    """
    rows = pg.execute(
        "SELECT c.relname, a.attname FROM pg_attribute a "
        "JOIN pg_class c ON c.oid = a.attrelid "
        "JOIN pg_namespace n ON n.oid = c.relnamespace "
        "WHERE n.nspname='public' AND c.relkind='r' "
        "AND a.attidentity IN ('d','a') "        # d = BY DEFAULT, a = ALWAYS
        "AND a.attnum > 0 AND NOT a.attisdropped "
        "ORDER BY c.relname, a.attnum").fetchall()
    done = 0
    for tbl, col in rows:
        seq = pg.execute(
            "SELECT pg_get_serial_sequence(%s, %s)",
            ("public." + config.qi(tbl), col)).fetchone()[0]
        if not seq:
            continue
        mx = pg.execute(
            "SELECT COALESCE(MAX(%s), 0) FROM %s"
            % (config.qi(col), config.qi(tbl))).fetchone()[0]
        # is_called = (mx > 0): con filas -> next id = mx+1; tabla vacia -> next id = 1
        pg.execute("SELECT setval(%s, GREATEST(%s, 1), %s)", (seq, mx, mx > 0))
        done += 1
    return done


# ------------------------------------------------------------------- orquestacion
def copy_data(tables=None, truncate=True, batch=5000, reset=True):
    """Copia los datos y (por defecto) re-sincroniza las secuencias. Devuelve total."""
    pg = config.connect_pg()
    pg.execute("SET session_replication_role = replica")  # FK off en esta sesion

    available = pg_base_tables(pg)
    if tables:
        want = {t.strip() for t in tables if t.strip()}
        selected = [t for t in available if t in want]
        missing = sorted(want - set(available))
        if missing:
            print("   (aviso: tablas no encontradas en el destino, se omiten: %s)"
                  % ", ".join(missing))
    else:
        selected = available
    if not selected:
        pg.close()
        raise SystemExit("ERROR: no hay tablas base para migrar (verifique el esquema destino).")

    mssql = config.connect_mssql()
    try:
        if truncate:
            print("==> Truncando %d tablas destino (RESTART IDENTITY CASCADE)" % len(selected))
            truncate_all(pg, selected)

        print("==> Copiando MSSQL -> PostgreSQL (preservando PK)")
        total = 0
        for t in selected:
            cols = pg_columns(pg, t)
            try:
                n = copy_into_pg(pg, t, cols, stream_mssql(mssql, t, cols, batch))
            except Exception as e:  # noqa: BLE001 - reportar la tabla y abortar (fail loud)
                raise SystemExit("ERROR copiando tabla %s: %s" % (t, e))
            total += n
            print("   %-42s %10d filas" % (t, n))

        if reset:
            k = reset_sequences(pg)
            print("==> Secuencias identity re-sincronizadas: %d" % k)

        pg.execute("SET session_replication_role = DEFAULT")
        print("==> Datos: %d filas en %d tablas." % (total, len(selected)))
        return total
    finally:
        mssql.close()
        pg.close()
