-- =====================================================================
-- Geus_ISP_DB  ·  01_schema.sql  ·  Tables (PK / FK / index / defaults)
-- =====================================================================
-- Target engine : PostgreSQL 18 (ICU)
-- Source        : Generated from the EF Core model (IspDbContext, Npgsql
--                 provider) via Database.GenerateCreateScript(), then
--                 reconciled against the tested corpus under
--                 ia-assets/pg-migration/ (25.08.22_Geus_ISP_DB_to_PG.psql).
-- Fidelity      : Column names / types / PK / FK / indexes / defaults are
--                 exactly what EF expects at runtime, so integration tests
--                 that exercise IspDbContext hit a schema identical to the
--                 model. Boolean defaults left as MSSQL '((0))'/'((1))' in
--                 the scaffolded model were normalized to false/true.
-- Apply order   : 00_init.sql -> 01_schema.sql -> 02_constraints_indexes.sql
--                 -> 03_views.sql
-- =====================================================================

CREATE TABLE "Country" (
    "IdCountry" integer GENERATED BY DEFAULT AS IDENTITY,
    "Country" character varying(100) NOT NULL,
    CONSTRAINT "PK_Country" PRIMARY KEY ("IdCountry")
);


CREATE TABLE "Terminal" (
    "IdTerminal" integer GENERATED BY DEFAULT AS IDENTITY,
    "AddressMac" character varying(50) NOT NULL,
    "HostName" character varying(50) NOT NULL,
    "Token" character varying(64) NOT NULL,
    CONSTRAINT "PK__Terminal__D9005501BD50951F" PRIMARY KEY ("IdTerminal")
);


CREATE TABLE "TermsGroup" (
    "IdTermsGroup" integer NOT NULL,
    "NameGroup" character varying(100) NOT NULL,
    CONSTRAINT "PK_TermsGroup" PRIMARY KEY ("IdTermsGroup")
);


CREATE TABLE "State" (
    "IdState" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdCountry" integer NOT NULL,
    "State" character varying(100) NOT NULL,
    CONSTRAINT "PK_State" PRIMARY KEY ("IdState"),
    CONSTRAINT "FK_State_Country" FOREIGN KEY ("IdCountry") REFERENCES "Country" ("IdCountry")
);


CREATE TABLE "Terms" (
    "IdTerms" integer NOT NULL,
    "IdTermsGroup" integer NOT NULL,
    "Term" character varying(100) NOT NULL,
    "Icon" text,
    "Visible" boolean NOT NULL,
    CONSTRAINT "PK_Terms" PRIMARY KEY ("IdTerms"),
    CONSTRAINT "FK_Terms_TermsGroup" FOREIGN KEY ("IdTermsGroup") REFERENCES "TermsGroup" ("IdTermsGroup")
);


CREATE TABLE "City" (
    "IdCity" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdState" integer NOT NULL,
    "City" character varying(100) NOT NULL,
    CONSTRAINT "PK_City" PRIMARY KEY ("IdCity"),
    CONSTRAINT "FK_City_State" FOREIGN KEY ("IdState") REFERENCES "State" ("IdState")
);


CREATE TABLE "DocumentTemplate" (
    "IdDocumentTemplate" integer NOT NULL,
    "IdTermDocument" integer NOT NULL,
    "DocumentTemplateName" character varying(100) NOT NULL,
    "Html" text NOT NULL,
    "JsonParameters" text NOT NULL,
    CONSTRAINT "PK__Document__21C151B1BF4AFE5C" PRIMARY KEY ("IdDocumentTemplate"),
    CONSTRAINT "FK_Terms_Document_DocumentTemplate" FOREIGN KEY ("IdTermDocument") REFERENCES "Terms" ("IdTerms")
);


CREATE TABLE "OnuStock" (
    "IdOnuStock" uuid NOT NULL DEFAULT ((gen_random_uuid())),
    "Mac" character varying(17) NOT NULL,
    "Consecutive" bigint NOT NULL,
    "Status" integer NOT NULL,
    "IdEmployee" integer,
    "IdContract" integer,
    "IdCompany" uuid NOT NULL,
    CONSTRAINT "PK_IdOnuStock" PRIMARY KEY ("IdOnuStock"),
    CONSTRAINT "FK_OnuStock_Terms" FOREIGN KEY ("Status") REFERENCES "Terms" ("IdTerms")
);


CREATE TABLE "Report" (
    "IdReport" integer NOT NULL,
    "IdTermReportCategory" integer NOT NULL,
    "Title" character varying(255) NOT NULL,
    "Description" character varying(1000) NOT NULL,
    "JsonParameters" text NOT NULL,
    "Query" text NOT NULL,
    "TableName" character varying(40) NOT NULL,
    CONSTRAINT "PK__TEMP_Rep__46F9D6CE5B1F7AE9" PRIMARY KEY ("IdReport"),
    CONSTRAINT "FK_Terms_Reports" FOREIGN KEY ("IdTermReportCategory") REFERENCES "Terms" ("IdTerms")
);


CREATE TABLE "ThirdPartyApplication" (
    "idThirdPartyApplication" integer NOT NULL,
    name character varying(99) NOT NULL,
    version character varying(50) NOT NULL,
    icon text NOT NULL,
    enable boolean NOT NULL,
    "IdTermThirdPartyApplicationType" integer NOT NULL,
    "JsonParameters" text,
    CONSTRAINT "PK__ThirdPar__4EA462DD3CBDFFC9" PRIMARY KEY ("idThirdPartyApplication"),
    CONSTRAINT "FK_Terms_ThirdPartyApplication_ThirdPartyApplicationType" FOREIGN KEY ("IdTermThirdPartyApplicationType") REFERENCES "Terms" ("IdTerms")
);


CREATE TABLE "Company" (
    "IdCompany" uuid NOT NULL DEFAULT ((gen_random_uuid())),
    "Nit" bigint NOT NULL,
    "Rutic" bigint,
    "BusinessName" character varying(100) NOT NULL,
    "IdCity" integer NOT NULL,
    "Enable" boolean NOT NULL,
    "StartDate" date NOT NULL,
    "EndDate" date,
    "Birthday" date NOT NULL,
    "iconCompany" text,
    "JsonParameters" text,
    CONSTRAINT "PK_Company" PRIMARY KEY ("IdCompany"),
    CONSTRAINT "FK__Company__IdCity__57DD0BE4" FOREIGN KEY ("IdCity") REFERENCES "City" ("IdCity")
);


CREATE TABLE "BranchCompany" (
    "IdBranchCompany" integer GENERATED BY DEFAULT AS IDENTITY,
    "idCompany" uuid NOT NULL,
    "BranchCompanyName" character varying(30) NOT NULL,
    CONSTRAINT "PK__BranchCo__6C35C0C5AD679F92" PRIMARY KEY ("IdBranchCompany"),
    CONSTRAINT "FK_BranchCompany_Company" FOREIGN KEY ("idCompany") REFERENCES "Company" ("IdCompany")
);


CREATE TABLE "CompanyCustomTermGroup" (
    "IdCompanyCustomTermGroup" integer NOT NULL,
    "IdTermControlCustomCompanyTerm" integer,
    "IdCompany" uuid,
    "Title" character varying(150),
    "Description" character varying(1000),
    CONSTRAINT "PK_IdCompanyCustomTermGroup" PRIMARY KEY ("IdCompanyCustomTermGroup"),
    CONSTRAINT "Fk_IdCompanyTermGroup" FOREIGN KEY ("IdCompany") REFERENCES "Company" ("IdCompany")
);


CREATE TABLE "CompanyEntityCustomField" (
    "IdCompanyEntityCustomField" uuid NOT NULL DEFAULT ((gen_random_uuid())),
    "IdCompany" uuid NOT NULL,
    "IdTermEntity" integer NOT NULL,
    "IdTermCustomField" integer NOT NULL,
    "CustomFieldName" character varying(100) NOT NULL,
    "IsRequired" boolean NOT NULL,
    "IsEnabled" boolean NOT NULL,
    CONSTRAINT "PK__CompanyE__DC2D4D9B802F4FEA" PRIMARY KEY ("IdCompanyEntityCustomField"),
    CONSTRAINT "FK_CompanyEntityCustomField_Company" FOREIGN KEY ("IdCompany") REFERENCES "Company" ("IdCompany"),
    CONSTRAINT "FK_Term_CompanyEntityCustomField_TermCustomField" FOREIGN KEY ("IdTermCustomField") REFERENCES "Terms" ("IdTerms"),
    CONSTRAINT "FK_Term_CompanyEntityCustomField_TermEntity" FOREIGN KEY ("IdTermEntity") REFERENCES "Terms" ("IdTerms")
);


CREATE TABLE "CompanyParameter" (
    "IdTermCompanyParameter" integer NOT NULL,
    "IdCompany" uuid NOT NULL,
    "Value" character varying(255) NOT NULL,
    "Enabled" boolean NOT NULL,
    "JsonParameters" text,
    CONSTRAINT "PK__CompanyP__4DD8B5794C5BE306" PRIMARY KEY ("IdTermCompanyParameter", "IdCompany"),
    CONSTRAINT "FK_CompanyParameter_Company" FOREIGN KEY ("IdCompany") REFERENCES "Company" ("IdCompany"),
    CONSTRAINT "FK_Terms_CompanyParameter_CompanyParameter" FOREIGN KEY ("IdTermCompanyParameter") REFERENCES "Terms" ("IdTerms")
);


CREATE TABLE "DocumentConsecutive" (
    "IdDocumentConsecutive" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdCompany" uuid NOT NULL,
    "IdTermDocumentConsecutive" integer,
    "Resolution" character varying(255),
    "BeginConsecutive" bigint NOT NULL,
    "CurrentConsecutive" bigint NOT NULL,
    "EndConsecutive" bigint NOT NULL,
    "CreateDate" date,
    "EnableConsecutive" boolean NOT NULL,
    "ExpirationDate" date,
    "PrefixConsecutive" character varying(6) NOT NULL,
    "IdDocumentTemplate" integer,
    CONSTRAINT "PK__Document__5EB06DF1CF845446" PRIMARY KEY ("IdDocumentConsecutive"),
    CONSTRAINT "FK_Consecutive_Company" FOREIGN KEY ("IdCompany") REFERENCES "Company" ("IdCompany"),
    CONSTRAINT "FK_Consecutive_Term" FOREIGN KEY ("IdTermDocumentConsecutive") REFERENCES "Terms" ("IdTerms"),
    CONSTRAINT "FK_DocumentTemplate_DocumentConsecutive" FOREIGN KEY ("IdDocumentTemplate") REFERENCES "DocumentTemplate" ("IdDocumentTemplate")
);


CREATE TABLE "Item" (
    "idItem" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdCompany" uuid NOT NULL,
    "IdTermTypeItem" integer NOT NULL,
    "UnitCost" numeric(19,4) NOT NULL,
    "ItemName" character varying(100) NOT NULL,
    "SaleCosto" numeric(19,4) NOT NULL,
    "JsonAccountingProductParameters" character varying(2048),
    "ThirdParty" boolean NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "IdEmployeeDeleted" integer,
    "DateTimeDeleted" timestamp without time zone,
    "DateTimeRecovery" timestamp without time zone,
    "IdEmployeeRecovery" integer,
    "IsDirty" boolean NOT NULL,
    CONSTRAINT "PK_Item" PRIMARY KEY ("idItem"),
    CONSTRAINT "FK_Item_Company" FOREIGN KEY ("IdCompany") REFERENCES "Company" ("IdCompany"),
    CONSTRAINT "FK_Item_Terms" FOREIGN KEY ("IdTermTypeItem") REFERENCES "Terms" ("IdTerms")
);


CREATE TABLE "Person" (
    "IdPerson" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TypePerson" integer NOT NULL,
    "TypeIdentification" integer NOT NULL,
    "Nuip" bigint NOT NULL,
    "Birthday" date NOT NULL,
    "IdCity" integer NOT NULL,
    "BusinessName" character varying(100),
    "Rh" integer NOT NULL,
    "Name" character varying(100),
    "SurName" character varying(100),
    "Gender" integer NOT NULL,
    "IsCertificated" boolean NOT NULL,
    "IdCompany" uuid NOT NULL,
    "ExpeditionDate" date,
    "isAlive" boolean NOT NULL DEFAULT true,
    "PersonHash" character varying(64),
    "IsBot" boolean NOT NULL,
    CONSTRAINT "PK_Person" PRIMARY KEY ("IdPerson"),
    CONSTRAINT "FK_Person_City" FOREIGN KEY ("IdCity") REFERENCES "City" ("IdCity"),
    CONSTRAINT "FK_Person_Company" FOREIGN KEY ("IdCompany") REFERENCES "Company" ("IdCompany"),
    CONSTRAINT "FK__Person__Gender__18B6AB08" FOREIGN KEY ("Gender") REFERENCES "Terms" ("IdTerms"),
    CONSTRAINT "FK__Person__Rh__17C286CF" FOREIGN KEY ("Rh") REFERENCES "Terms" ("IdTerms"),
    CONSTRAINT "FK__Person__TypeIden__15DA3E5D" FOREIGN KEY ("TypeIdentification") REFERENCES "Terms" ("IdTerms"),
    CONSTRAINT "FK__Person__TypePers__14E61A24" FOREIGN KEY ("TypePerson") REFERENCES "Terms" ("IdTerms")
);


CREATE TABLE "PlanService" (
    "IdPlanService" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdCompany" uuid NOT NULL,
    "PlanService" character varying(100) NOT NULL,
    "Description" character varying(255) NOT NULL,
    "Enable" boolean NOT NULL,
    "JsonParameters" text,
    "IsMigrated" boolean NOT NULL,
    "IdEmployeeLastMigrated" integer,
    "DateTimeLastMigrated" timestamp without time zone,
    "IsDeleted" boolean NOT NULL,
    "IdEmployeeDeleted" integer,
    "DateTimeDeteled" timestamp without time zone,
    "DateTimeRecovery" timestamp without time zone,
    "IdEmployeeRecovery" integer,
    CONSTRAINT "PK_PlanService" PRIMARY KEY ("IdPlanService"),
    CONSTRAINT "FK_PlanService_Company" FOREIGN KEY ("IdCompany") REFERENCES "Company" ("IdCompany")
);


CREATE TABLE "ThirdPartyApplicationCompanyParameter" (
    "idThirdPartyApplicationCompanyParameter" integer NOT NULL,
    "idCompany" uuid NOT NULL,
    "idThirdPartyApplication" integer NOT NULL,
    "jsonParameters" text NOT NULL,
    enable boolean NOT NULL,
    CONSTRAINT "PK__ThirdPar__8942859EA7EE9050" PRIMARY KEY ("idThirdPartyApplicationCompanyParameter"),
    CONSTRAINT "FK_ThirdPartyApplicationCompanyParameter_Company" FOREIGN KEY ("idCompany") REFERENCES "Company" ("IdCompany"),
    CONSTRAINT "FK_ThirdPartyApplicationCompanyParameter_ThirdPartyApplication" FOREIGN KEY ("idThirdPartyApplication") REFERENCES "ThirdPartyApplication" ("idThirdPartyApplication")
);


CREATE TABLE "Zone" (
    "IdZone" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdCompany" uuid NOT NULL,
    "Title" character varying(100) NOT NULL,
    "Description" character varying(1000) NOT NULL,
    "JsonParameters" text NOT NULL,
    CONSTRAINT "PK__Zone__F631C121D0090DBC" PRIMARY KEY ("IdZone"),
    CONSTRAINT "FK_Zone_Company" FOREIGN KEY ("IdCompany") REFERENCES "Company" ("IdCompany")
);


CREATE TABLE "Office" (
    "IdOffice" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdBranchCompany" integer NOT NULL,
    "OfficeName" character varying(50),
    CONSTRAINT "PK__Office__57A12F4FE469C26B" PRIMARY KEY ("IdOffice"),
    CONSTRAINT "FK_Office_BranchCompany" FOREIGN KEY ("IdBranchCompany") REFERENCES "BranchCompany" ("IdBranchCompany")
);


CREATE TABLE "CompanyCustomTerm" (
    "IdCompanyCustomTerm" integer NOT NULL,
    "IdCompany" uuid,
    "IdCompanyCustomTermGroup" integer,
    "Term" character varying(100),
    "Icon" text,
    "Enabled" boolean NOT NULL,
    CONSTRAINT "PK_IdCompanyCustomTerm" PRIMARY KEY ("IdCompanyCustomTerm"),
    CONSTRAINT "Fk_IdCompanyCustomTermGroups" FOREIGN KEY ("IdCompanyCustomTermGroup") REFERENCES "CompanyCustomTermGroup" ("IdCompanyCustomTermGroup"),
    CONSTRAINT "Fk_IdCompanyTerm" FOREIGN KEY ("IdCompany") REFERENCES "Company" ("IdCompany")
);


CREATE TABLE "BranchCompanyDocumentConsecutive" (
    "IdBranchCompanyDocumentConsecutive" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdBranchCompany" integer NOT NULL,
    "IdDocumentConsecutive" integer NOT NULL,
    "IdDocumentTemplate" integer,
    CONSTRAINT "PK__BranchCo__ACE64789D926A36D" PRIMARY KEY ("IdBranchCompanyDocumentConsecutive"),
    CONSTRAINT "FK_BranchCompanyDocumentConsecutive_BranchCompany" FOREIGN KEY ("IdBranchCompany") REFERENCES "BranchCompany" ("IdBranchCompany"),
    CONSTRAINT "FK_BranchCompanyDocumentConsecutive_DocumentConsecutive" FOREIGN KEY ("IdDocumentConsecutive") REFERENCES "DocumentConsecutive" ("IdDocumentConsecutive"),
    CONSTRAINT "FK_DocumentTemplate_BranchCompanyDocumentConsecutive" FOREIGN KEY ("IdDocumentTemplate") REFERENCES "DocumentTemplate" ("IdDocumentTemplate")
);


CREATE TABLE "GenericService" (
    "idItem" integer NOT NULL,
    "idTermGenericService" integer NOT NULL,
    "JsonParameters" text,
    CONSTRAINT "PK__GenericS__AD194268D6C4B7B9" PRIMARY KEY ("idItem"),
    CONSTRAINT "FK_Term_GenericService" FOREIGN KEY ("idTermGenericService") REFERENCES "Terms" ("IdTerms"),
    CONSTRAINT "PK_Fk_Item_GenericService" FOREIGN KEY ("idItem") REFERENCES "Item" ("idItem")
);


CREATE TABLE "TicketType" (
    "idItem" integer NOT NULL,
    "idTermTicketAction" integer NOT NULL,
    score integer NOT NULL,
    "RequiredInvoice" boolean NOT NULL,
    "JsonParameters" text,
    CONSTRAINT "PK__TicketTy__AD194268FA31BB27" PRIMARY KEY ("idItem"),
    CONSTRAINT "FK_Term_TicketType" FOREIGN KEY ("idTermTicketAction") REFERENCES "Terms" ("IdTerms"),
    CONSTRAINT "PK_Fk_Item_TicketType" FOREIGN KEY ("idItem") REFERENCES "Item" ("idItem")
);


CREATE TABLE "Employee" (
    "IdEmployee" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdCompany" uuid NOT NULL,
    "IdPerson" bigint NOT NULL,
    "BeginDate" date NOT NULL,
    "IdTermJobPosition" integer NOT NULL,
    "EndDate" date,
    "Avatar" text,
    CONSTRAINT "PK_Employee" PRIMARY KEY ("IdEmployee"),
    CONSTRAINT "FK_Employee_Company" FOREIGN KEY ("IdCompany") REFERENCES "Company" ("IdCompany"),
    CONSTRAINT "FK_Employee_Person" FOREIGN KEY ("IdPerson") REFERENCES "Person" ("IdPerson"),
    CONSTRAINT "FK_Employee_Terms" FOREIGN KEY ("IdTermJobPosition") REFERENCES "Terms" ("IdTerms")
);


CREATE TABLE "PersonEmail" (
    "IdPersonEmail" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdPerson" bigint NOT NULL,
    "Email" character varying(100) NOT NULL,
    "Enable" boolean NOT NULL,
    "EmailVerification" boolean NOT NULL,
    "IdTermTypeEmail" integer NOT NULL,
    CONSTRAINT "PK__PersonEm__C010140467E97FE9" PRIMARY KEY ("IdPersonEmail"),
    CONSTRAINT "FK_Email_Term" FOREIGN KEY ("IdTermTypeEmail") REFERENCES "Terms" ("IdTerms"),
    CONSTRAINT "FK_Person_Email" FOREIGN KEY ("IdPerson") REFERENCES "Person" ("IdPerson")
);


CREATE TABLE "PersonPhoneNumber" (
    "IdPhoneNumber" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdTermTypePhonNumber" integer NOT NULL,
    "IdCity" integer NOT NULL,
    "IsMovil" boolean NOT NULL,
    "PhoneNumber" character varying(20) NOT NULL,
    "Enable" boolean NOT NULL,
    "PhoneNumberVerification" boolean NOT NULL,
    "IdPerson" bigint NOT NULL,
    "WhatsApp" boolean DEFAULT false,
    CONSTRAINT "PK__PersonPh__1DEA28991B0247ED" PRIMARY KEY ("IdPhoneNumber"),
    CONSTRAINT "FK_City_PhoneNumber" FOREIGN KEY ("IdCity") REFERENCES "City" ("IdCity"),
    CONSTRAINT "FK_Person_PhoneNumber" FOREIGN KEY ("IdPerson") REFERENCES "Person" ("IdPerson"),
    CONSTRAINT "FK_PhoneNumber_Term" FOREIGN KEY ("IdTermTypePhonNumber") REFERENCES "Terms" ("IdTerms")
);


CREATE TABLE "PlanServiceDetail" (
    "IdDetailService" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdPlanService" integer NOT NULL,
    "Cost" numeric(19,4) NOT NULL,
    "IdItemService" integer NOT NULL,
    CONSTRAINT "PK_DetaillService" PRIMARY KEY ("IdDetailService"),
    CONSTRAINT "FK_DetaillService_Item" FOREIGN KEY ("IdItemService") REFERENCES "Item" ("idItem"),
    CONSTRAINT "FK__PlanServi__IdPla__4589517F" FOREIGN KEY ("IdPlanService") REFERENCES "PlanService" ("IdPlanService")
);


CREATE TABLE "Neighborhood" (
    "IdNeighborhood" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdCity" integer NOT NULL,
    "IdCompany" uuid NOT NULL,
    "Neighborhood" character varying(100) NOT NULL,
    "Enabled" boolean NOT NULL,
    "JsonParameters" text,
    "IdZone" integer NOT NULL,
    CONSTRAINT "PK_Neighborhood" PRIMARY KEY ("IdNeighborhood"),
    CONSTRAINT "FK_Neighborhood_City" FOREIGN KEY ("IdCity") REFERENCES "City" ("IdCity"),
    CONSTRAINT "FK_Neighborhood_Company" FOREIGN KEY ("IdCompany") REFERENCES "Company" ("IdCompany"),
    CONSTRAINT "FK_Zone_Neighborhood" FOREIGN KEY ("IdZone") REFERENCES "Zone" ("IdZone")
);


CREATE TABLE "ZonePlanService" (
    "IdZonePlanService" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdPlanService" integer NOT NULL,
    "IdZone" integer NOT NULL,
    "Include" boolean NOT NULL,
    CONSTRAINT "PK__ZonePlan__678298C52171BF2A" PRIMARY KEY ("IdZonePlanService"),
    CONSTRAINT "FK_PlanService_ZonePlanService" FOREIGN KEY ("IdPlanService") REFERENCES "PlanService" ("IdPlanService"),
    CONSTRAINT "FK_Zone_ZonePlanService" FOREIGN KEY ("IdZone") REFERENCES "Zone" ("IdZone")
);


CREATE TABLE "CashRegister" (
    "IdCashRegister" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdOffice" integer NOT NULL,
    "AddressMac" character varying(50) NOT NULL,
    "HostName" character varying(50) NOT NULL,
    "Token" character varying(64) NOT NULL,
    "Enable" boolean NOT NULL,
    "IsBot" boolean NOT NULL,
    "Name" character varying(4000),
    "IdTerminal" integer,
    CONSTRAINT "PK__CashRegi__42A16C55AAB8E8E8" PRIMARY KEY ("IdCashRegister"),
    CONSTRAINT "FK_CashRegister_Office" FOREIGN KEY ("IdOffice") REFERENCES "Office" ("IdOffice"),
    CONSTRAINT "FK_CashRegister_Terminal" FOREIGN KEY ("IdTerminal") REFERENCES "Terminal" ("IdTerminal")
);


CREATE TABLE "CompanyCustomTermChild" (
    "IdCompanyCustomTermChild" integer NOT NULL,
    "IdCompanyCustomTermParent" integer,
    CONSTRAINT "PK_IdCompanyCustomTermParentChild" PRIMARY KEY ("IdCompanyCustomTermChild"),
    CONSTRAINT "Fk_IdCompanyCustomTermChild" FOREIGN KEY ("IdCompanyCustomTermChild") REFERENCES "CompanyCustomTerm" ("IdCompanyCustomTerm"),
    CONSTRAINT "Fk_IdCompanyCustomTermParent" FOREIGN KEY ("IdCompanyCustomTermParent") REFERENCES "CompanyCustomTerm" ("IdCompanyCustomTerm")
);


CREATE TABLE "Address" (
    "IdAddress" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdNeighborhood" integer NOT NULL,
    "IdCity" integer NOT NULL,
    "idCompany" uuid NOT NULL,
    "Address" character varying(300) NOT NULL,
    "Latitud" numeric(18,10),
    "Longitud" numeric(18,10),
    "IdTermSocioeconomic" integer,
    CONSTRAINT "PK_Address" PRIMARY KEY ("IdAddress"),
    CONSTRAINT "FK_Address_City" FOREIGN KEY ("IdCity") REFERENCES "City" ("IdCity"),
    CONSTRAINT "FK_Address_Company" FOREIGN KEY ("idCompany") REFERENCES "Company" ("IdCompany"),
    CONSTRAINT "FK_Address_Neighborhood" FOREIGN KEY ("IdNeighborhood") REFERENCES "Neighborhood" ("IdNeighborhood"),
    CONSTRAINT "FK_Terms_Addres_Socioeconomic" FOREIGN KEY ("IdTermSocioeconomic") REFERENCES "Terms" ("IdTerms")
);


CREATE TABLE "NeighborhoodPlanService" (
    "IdNeighborhoodPlanService" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdPlanService" integer NOT NULL,
    "IdNeighborhood" integer NOT NULL,
    "Include" boolean NOT NULL,
    CONSTRAINT "PK__Neighbor__7F66A5A7C93E8B34" PRIMARY KEY ("IdNeighborhoodPlanService"),
    CONSTRAINT "FK_Neighborhood_NeighborhoodPlanService" FOREIGN KEY ("IdNeighborhood") REFERENCES "Neighborhood" ("IdNeighborhood"),
    CONSTRAINT "FK_PlanService_NeighborhoodPlanService" FOREIGN KEY ("IdPlanService") REFERENCES "PlanService" ("IdPlanService")
);


CREATE TABLE "CashRegisterLog" (
    "IdCashRegisterLog" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdEmployee" integer NOT NULL,
    "IdCashRegister" integer NOT NULL,
    "DateOpen" timestamp without time zone NOT NULL,
    "DateClose" timestamp without time zone,
    "CashClose" numeric(19,4),
    "InitBalance" numeric(19,4) NOT NULL,
    "LeftBalance" numeric(19,4),
    CONSTRAINT "PK__CashRegi__1FAE3D715FE87807" PRIMARY KEY ("IdCashRegisterLog"),
    CONSTRAINT "FK_CashRegisterLog_CashRegister" FOREIGN KEY ("IdCashRegister") REFERENCES "CashRegister" ("IdCashRegister"),
    CONSTRAINT "FK_CashRegisterLog_Employee" FOREIGN KEY ("IdEmployee") REFERENCES "Employee" ("IdEmployee")
);


CREATE TABLE "Contract" (
    "IdContract" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdCompany" uuid NOT NULL,
    "IdAddressFacturation" bigint NOT NULL,
    "IdAddressInstalation" bigint NOT NULL,
    "IdPlanService" integer NOT NULL,
    "IdTermContractStatus" integer NOT NULL,
    "IdPerson" bigint NOT NULL,
    "BeginDate" date,
    "EndDate" date,
    "CreateDate" date NOT NULL,
    "IdBranchCompany" integer NOT NULL,
    "Consecutive" bigint NOT NULL,
    prefix character varying(3) NOT NULL,
    "IdTermTicketAction" integer NOT NULL,
    "LastChangeDateTime" timestamp without time zone NOT NULL,
    "IdEmployeeLastChange" integer NOT NULL,
    "LastExecutionDateTime" timestamp without time zone NOT NULL,
    "JsonParameters" text,
    CONSTRAINT "PK_Contract" PRIMARY KEY ("IdContract"),
    CONSTRAINT "FK_Contract_Address" FOREIGN KEY ("IdAddressFacturation") REFERENCES "Address" ("IdAddress"),
    CONSTRAINT "FK_Contract_Address1" FOREIGN KEY ("IdAddressInstalation") REFERENCES "Address" ("IdAddress"),
    CONSTRAINT "FK_Contract_BranchCompany" FOREIGN KEY ("IdBranchCompany") REFERENCES "BranchCompany" ("IdBranchCompany"),
    CONSTRAINT "FK_Contract_Company" FOREIGN KEY ("IdCompany") REFERENCES "Company" ("IdCompany"),
    CONSTRAINT "FK_Contract_Person" FOREIGN KEY ("IdPerson") REFERENCES "Person" ("IdPerson"),
    CONSTRAINT "FK_Contract_PlanService" FOREIGN KEY ("IdPlanService") REFERENCES "PlanService" ("IdPlanService"),
    CONSTRAINT "FK_Contract_Terms" FOREIGN KEY ("IdTermContractStatus") REFERENCES "Terms" ("IdTerms"),
    CONSTRAINT "FK_Employee_Contract_IdEmployeeLastChange" FOREIGN KEY ("IdEmployeeLastChange") REFERENCES "Employee" ("IdEmployee"),
    CONSTRAINT "FK_Term_Contract_IdTermTicketAction" FOREIGN KEY ("IdTermTicketAction") REFERENCES "Terms" ("IdTerms")
);


CREATE TABLE "HorizontalProperty" (
    "idHorizontalProperty" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdAddress" bigint NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Composition" text NOT NULL,
    CONSTRAINT "PK_HorizontalProperty" PRIMARY KEY ("idHorizontalProperty"),
    CONSTRAINT "FK_HorizontalProperty_Address" FOREIGN KEY ("IdAddress") REFERENCES "Address" ("IdAddress")
);


CREATE TABLE "Expense" (
    "IdExpense" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdCompanyCustomTermExpenseType" integer,
    "IdCashRegisterLog" integer,
    "Subject" character varying(80),
    "Description" text,
    "ExpenseValue" numeric(19,4),
    "CreateDateTime" timestamp without time zone,
    "DoneDateTime" timestamp without time zone,
    "IdTermStatusExpense" integer,
    "Done" boolean,
    "JsonParameters" text,
    CONSTRAINT "PK_IdExpense" PRIMARY KEY ("IdExpense"),
    CONSTRAINT "Fk_IdCashRegisterLog" FOREIGN KEY ("IdCashRegisterLog") REFERENCES "CashRegisterLog" ("IdCashRegisterLog"),
    CONSTRAINT "Fk_IdCompanyCustomTermExpenseType" FOREIGN KEY ("IdCompanyCustomTermExpenseType") REFERENCES "CompanyCustomTerm" ("IdCompanyCustomTerm"),
    CONSTRAINT "Fk_IdTermStatusExpense" FOREIGN KEY ("IdTermStatusExpense") REFERENCES "Terms" ("IdTerms")
);


CREATE TABLE "ContractConnection" (
    "IdConnection" uuid NOT NULL DEFAULT ((gen_random_uuid())),
    "IdContract" bigint NOT NULL,
    "IdTermGenericService" integer NOT NULL,
    "IdTermConnectionType" integer NOT NULL,
    "JsonParameters" text NOT NULL,
    "ConnectionHash" character varying(64) NOT NULL,
    "CreateDateTime" timestamp without time zone NOT NULL,
    CONSTRAINT "PK__Contract__75D79D3BB6EDF66F" PRIMARY KEY ("IdConnection"),
    CONSTRAINT "FK_ContractConnection_Contract" FOREIGN KEY ("IdContract") REFERENCES "Contract" ("IdContract"),
    CONSTRAINT "FK_Terms_ContractConnection_ConnectionType" FOREIGN KEY ("IdTermConnectionType") REFERENCES "Terms" ("IdTerms"),
    CONSTRAINT "FK_Terms_ContractConnection_GenericService" FOREIGN KEY ("IdTermGenericService") REFERENCES "Terms" ("IdTerms")
);


CREATE TABLE "ContractConnectionHistory" (
    "IdConnection" uuid NOT NULL DEFAULT ((gen_random_uuid())),
    "IdContract" bigint NOT NULL,
    "IdTermGenericService" integer NOT NULL,
    "IdTermConnectionType" integer NOT NULL,
    "JsonParameters" text NOT NULL,
    "ConnectionHash" character varying(64) NOT NULL,
    "CreateDateTime" timestamp without time zone NOT NULL,
    CONSTRAINT "PK__Contract__75D79D3BC2263C9A" PRIMARY KEY ("IdConnection"),
    CONSTRAINT "FK_ContractConnectionHistory_Contract" FOREIGN KEY ("IdContract") REFERENCES "Contract" ("IdContract"),
    CONSTRAINT "FK_Terms_ContractConnectionHistory_ConnectionType" FOREIGN KEY ("IdTermConnectionType") REFERENCES "Terms" ("IdTerms"),
    CONSTRAINT "FK_Terms_ContractConnectionHistory_GenericService" FOREIGN KEY ("IdTermGenericService") REFERENCES "Terms" ("IdTerms")
);


CREATE TABLE "ContractCustomField" (
    "IdContract" bigint NOT NULL,
    "IdCompanyEntityCustomField" uuid NOT NULL,
    "CustomFieldName" character varying(100) NOT NULL,
    "GenericValue" character varying(100) NOT NULL,
    CONSTRAINT "PK_ContractCustomField" PRIMARY KEY ("IdContract", "IdCompanyEntityCustomField"),
    CONSTRAINT "FK_ContractCustomField_CompanyEntityCustomField" FOREIGN KEY ("IdCompanyEntityCustomField") REFERENCES "CompanyEntityCustomField" ("IdCompanyEntityCustomField"),
    CONSTRAINT "FK_ContractCustomField_Contract" FOREIGN KEY ("IdContract") REFERENCES "Contract" ("IdContract")
);


CREATE TABLE "Invoice" (
    "IdInvoice" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdCompany" uuid NOT NULL,
    "idBranchCompany" integer NOT NULL,
    "IdContract" bigint NOT NULL,
    "Consecutive" bigint NOT NULL,
    "Prefix" character varying(3),
    "CreateDate" timestamp without time zone NOT NULL,
    "FinishDate" timestamp without time zone NOT NULL,
    "TotalPay" numeric(19,4) NOT NULL,
    "TotalInvoice" numeric(19,4) NOT NULL,
    "Pay" boolean NOT NULL,
    "ElectronicInvoiceHash" character varying(64) NOT NULL,
    CONSTRAINT "PK_Invoice" PRIMARY KEY ("IdInvoice"),
    CONSTRAINT "FK_Invoice_Company" FOREIGN KEY ("IdCompany") REFERENCES "Company" ("IdCompany"),
    CONSTRAINT "FK_Invoice_Contract" FOREIGN KEY ("IdContract") REFERENCES "Contract" ("IdContract"),
    CONSTRAINT "Fk_Invoice_BranchCompany" FOREIGN KEY ("idBranchCompany") REFERENCES "BranchCompany" ("IdBranchCompany")
);


CREATE TABLE "InvoiceRecurrent" (
    "IdInvoiceRecurrent" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdContract" bigint NOT NULL,
    "IdItemService" integer NOT NULL,
    "Position" integer NOT NULL,
    date date NOT NULL,
    pay boolean NOT NULL,
    "payDate" date,
    CONSTRAINT "PK__InvoiceR__2AC4ACABB08C48E5" PRIMARY KEY ("IdInvoiceRecurrent"),
    CONSTRAINT "FK_InvoiceRecurrent_Contract" FOREIGN KEY ("IdContract") REFERENCES "Contract" ("IdContract"),
    CONSTRAINT "FK_InvoiceRecurrent_Item" FOREIGN KEY ("IdItemService") REFERENCES "Item" ("idItem")
);


CREATE TABLE "OnlinePay" (
    "IdOnlinePay" uuid NOT NULL DEFAULT ((gen_random_uuid())),
    "IdCompany" uuid NOT NULL,
    "IdContract" bigint NOT NULL,
    "idThirdPartyApplication" integer NOT NULL,
    "IdTermOnlinePayStatus" integer NOT NULL,
    "IdSourceOnlinePay" character varying(64),
    "ReportedDateTime" timestamp without time zone DEFAULT ((now())),
    "Prefix" character varying(6) NOT NULL,
    "Consecutive" bigint NOT NULL,
    "CreateDateTime" timestamp without time zone DEFAULT ((now())),
    "JSONPayLoad" text NOT NULL,
    "JSONPayLoadHash" character varying(64) NOT NULL,
    "Pay" boolean DEFAULT false,
    "OnlinePayValue" numeric(19,4) NOT NULL,
    CONSTRAINT "PK_OnlinePay" PRIMARY KEY ("IdOnlinePay"),
    CONSTRAINT "FK_OnlinePayTerms_Terms" FOREIGN KEY ("IdTermOnlinePayStatus") REFERENCES "Terms" ("IdTerms"),
    CONSTRAINT "FK_OnlinePay_Company" FOREIGN KEY ("IdCompany") REFERENCES "Company" ("IdCompany"),
    CONSTRAINT "FK_OnlinePay_Contract" FOREIGN KEY ("IdContract") REFERENCES "Contract" ("IdContract"),
    CONSTRAINT "FK_OnlinePay_ThirdPartyApplication" FOREIGN KEY ("idThirdPartyApplication") REFERENCES "ThirdPartyApplication" ("idThirdPartyApplication")
);


CREATE TABLE "SupportTicket" (
    "IdSupportTicket" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdCompany" uuid NOT NULL,
    "IdEmployee" integer NOT NULL,
    "IdContract" bigint NOT NULL,
    "DateCreate" timestamp without time zone NOT NULL,
    "IdItemTypeSupportTicket" integer NOT NULL,
    "IdTermTicketScheduleType" integer NOT NULL,
    "SubscriberNotes" text,
    "TechnicianNotes" text,
    "Done" boolean NOT NULL,
    "Schedule_Date" timestamp without time zone NOT NULL,
    "idBranchCompany" integer NOT NULL,
    "Consecutive" bigint NOT NULL,
    prefix character varying(3) NOT NULL,
    "SubscriberSign" text,
    "JSONPayload" character varying(4000),
    "IsPassAudit" boolean,
    CONSTRAINT "PK_SupportTicket" PRIMARY KEY ("IdSupportTicket"),
    CONSTRAINT "FK_SupportTIcket_Term" FOREIGN KEY ("IdTermTicketScheduleType") REFERENCES "Terms" ("IdTerms"),
    CONSTRAINT "FK_SupportTicket_BranchCompany" FOREIGN KEY ("idBranchCompany") REFERENCES "BranchCompany" ("IdBranchCompany"),
    CONSTRAINT "FK_SupportTicket_Company" FOREIGN KEY ("IdCompany") REFERENCES "Company" ("IdCompany"),
    CONSTRAINT "FK_SupportTicket_Contract" FOREIGN KEY ("IdContract") REFERENCES "Contract" ("IdContract"),
    CONSTRAINT "FK_SupportTicket_Employee" FOREIGN KEY ("IdEmployee") REFERENCES "Employee" ("IdEmployee"),
    CONSTRAINT "FK_SupportTicket_Item" FOREIGN KEY ("IdItemTypeSupportTicket") REFERENCES "Item" ("idItem")
);


CREATE TABLE "Voucher" (
    "IdVoucher" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdContract" bigint NOT NULL,
    "IdCashRegisterLog" integer NOT NULL,
    "IdCompany" uuid NOT NULL,
    "Date" timestamp without time zone NOT NULL,
    prefix character varying(3) NOT NULL,
    "Consecutive" bigint NOT NULL,
    "idBranchCompany" integer NOT NULL,
    "IdTermDocumentType" integer NOT NULL,
    "ElectronicInvoiceHash" character varying(64) NOT NULL,
    "IdTermVoucherStatus" integer NOT NULL,
    "PayDate" date NOT NULL,
    "TotalPay" numeric(19,4) NOT NULL,
    CONSTRAINT "PK_Voucher" PRIMARY KEY ("IdVoucher"),
    CONSTRAINT "FK_Voucher_BranchCompany" FOREIGN KEY ("idBranchCompany") REFERENCES "BranchCompany" ("IdBranchCompany"),
    CONSTRAINT "FK_Voucher_CashRegisterLog" FOREIGN KEY ("IdCashRegisterLog") REFERENCES "CashRegisterLog" ("IdCashRegisterLog"),
    CONSTRAINT "FK_Voucher_Company" FOREIGN KEY ("IdCompany") REFERENCES "Company" ("IdCompany"),
    CONSTRAINT "FK_Voucher_Contract" FOREIGN KEY ("IdContract") REFERENCES "Contract" ("IdContract"),
    CONSTRAINT "FK_Voucher_TermDocument" FOREIGN KEY ("IdTermDocumentType") REFERENCES "Terms" ("IdTerms"),
    CONSTRAINT "FK__Voucher__IdTermV__0B7CAB7B" FOREIGN KEY ("IdTermVoucherStatus") REFERENCES "Terms" ("IdTerms")
);


CREATE TABLE "AddressHorizontalProperty" (
    "IdHorizontalProperty" integer NOT NULL,
    "IdAddress" bigint NOT NULL,
    CONSTRAINT "PK_AddressHorizontalProperty" PRIMARY KEY ("IdHorizontalProperty", "IdAddress"),
    CONSTRAINT "FK_AddressHorizontalProperty_Address" FOREIGN KEY ("IdAddress") REFERENCES "Address" ("IdAddress"),
    CONSTRAINT "FK_AddressHorizontalProperty_HorizontalProperty" FOREIGN KEY ("IdHorizontalProperty") REFERENCES "HorizontalProperty" ("idHorizontalProperty")
);


CREATE TABLE "InvoiceDetail" (
    "IdInvoiceDetail" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdItem" integer NOT NULL,
    "IdInvoice" bigint NOT NULL,
    "Descripction" text,
    "SaleCost" numeric(19,4) NOT NULL,
    "BuyCost" numeric(19,4) NOT NULL,
    "Quantity" double precision NOT NULL,
    "TotalInvoiceDetail" numeric(19,4) NOT NULL,
    "TotalPay" numeric(19,4) NOT NULL,
    pay boolean NOT NULL,
    CONSTRAINT "PK_InvoiceDetail" PRIMARY KEY ("IdInvoiceDetail"),
    CONSTRAINT "FK_InvoiceDetail_Invoice" FOREIGN KEY ("IdInvoice") REFERENCES "Invoice" ("IdInvoice"),
    CONSTRAINT "FK_InvoiceDetail_Item" FOREIGN KEY ("IdItem") REFERENCES "Item" ("idItem")
);


CREATE TABLE "OnlinePayLog" (
    "IdOnlinePayLog" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdOnlinePay" uuid,
    "IdTermOnlinePayStatus" integer NOT NULL,
    "JSONResponse" text NOT NULL,
    "ReportedDateTime" timestamp without time zone DEFAULT ((now())),
    CONSTRAINT "PK_OnlinePayLog" PRIMARY KEY ("IdOnlinePayLog"),
    CONSTRAINT "FK_OnlinePayLogTerms_Terms" FOREIGN KEY ("IdTermOnlinePayStatus") REFERENCES "Terms" ("IdTerms"),
    CONSTRAINT "FK_OnlinePayLog_OnlinePay" FOREIGN KEY ("IdOnlinePay") REFERENCES "OnlinePay" ("IdOnlinePay")
);


CREATE TABLE "SupportTicketSchedule" (
    "IdSchedule" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdSupportTicket" bigint NOT NULL,
    "ScheduleDate" timestamp without time zone NOT NULL,
    "IdTermTicketScheduleType" integer NOT NULL,
    "IdEmployee" integer NOT NULL,
    "IdTermTicketScheduleTypeReason" integer NOT NULL,
    "Description" text,
    CONSTRAINT "PK_Schedule" PRIMARY KEY ("IdSchedule"),
    CONSTRAINT "FK_ScheduleReason_Terms" FOREIGN KEY ("IdTermTicketScheduleTypeReason") REFERENCES "Terms" ("IdTerms"),
    CONSTRAINT "FK_Schedule_Employee" FOREIGN KEY ("IdEmployee") REFERENCES "Employee" ("IdEmployee"),
    CONSTRAINT "FK_Schedule_SupportTicket" FOREIGN KEY ("IdSupportTicket") REFERENCES "SupportTicket" ("IdSupportTicket"),
    CONSTRAINT "FK_Schedule_Terms" FOREIGN KEY ("IdTermTicketScheduleType") REFERENCES "Terms" ("IdTerms")
);


CREATE TABLE "VoucherPaymentMethods" (
    "IdVoucherPaymentMethods" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdVoucher" bigint NOT NULL,
    "IdTermTypePaymentMethod" integer NOT NULL,
    "IdTermTypeCard" integer NOT NULL,
    "IdTermBank" integer NOT NULL,
    "IdTermFranchise" integer NOT NULL,
    "Cus" character varying(50),
    "PayValue" numeric(19,4) NOT NULL,
    "PayChange" numeric(19,4) NOT NULL,
    CONSTRAINT "PK__VoucherP__9AFA44144044E5E9" PRIMARY KEY ("IdVoucherPaymentMethods"),
    CONSTRAINT "FK_VoucherPaymentMethods_Term_Bank" FOREIGN KEY ("IdTermBank") REFERENCES "Terms" ("IdTerms"),
    CONSTRAINT "FK_VoucherPaymentMethods_Term_Card" FOREIGN KEY ("IdTermTypeCard") REFERENCES "Terms" ("IdTerms"),
    CONSTRAINT "FK_VoucherPaymentMethods_Term_Franchise" FOREIGN KEY ("IdTermFranchise") REFERENCES "Terms" ("IdTerms"),
    CONSTRAINT "FK_VoucherPaymentMethods_Term_Payment" FOREIGN KEY ("IdTermTypePaymentMethod") REFERENCES "Terms" ("IdTerms"),
    CONSTRAINT "FK__VoucherPa__IdVou__220B0B18" FOREIGN KEY ("IdVoucher") REFERENCES "Voucher" ("IdVoucher")
);


CREATE TABLE "InvoiceRecurrentDetail" (
    "IdInvoiceRecurrentDetail" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdInvoiceRecurrent" integer NOT NULL,
    "IdInvoiceDetail" bigint NOT NULL,
    CONSTRAINT "PK__InvoiceR__E834F5AF71C703F3" PRIMARY KEY ("IdInvoiceRecurrentDetail"),
    CONSTRAINT "FK_InvoiceRecurrenDetail_InvoiceDetail" FOREIGN KEY ("IdInvoiceDetail") REFERENCES "InvoiceDetail" ("IdInvoiceDetail"),
    CONSTRAINT "FK_InvoiceRecurrent_InvoiceRecurrentDetail" FOREIGN KEY ("IdInvoiceRecurrent") REFERENCES "InvoiceRecurrent" ("IdInvoiceRecurrent")
);


CREATE TABLE "VoucherDetail" (
    "IdVoucherDetail" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdInvoiceDetail" bigint NOT NULL,
    "IdVoucher" bigint NOT NULL,
    "PayValue" numeric(19,4) NOT NULL,
    CONSTRAINT "PK_VoucherDetail" PRIMARY KEY ("IdVoucherDetail"),
    CONSTRAINT "FK_VoucherDetail_InvoiceDetail" FOREIGN KEY ("IdInvoiceDetail") REFERENCES "InvoiceDetail" ("IdInvoiceDetail"),
    CONSTRAINT "FK_VoucherDetail_Voucher" FOREIGN KEY ("IdVoucher") REFERENCES "Voucher" ("IdVoucher")
);


CREATE TABLE "SupportTicketScheduleAudit" (
    "IdSupportTicketScheduleAudit" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdSupportTicketSchedule" integer NOT NULL,
    "IdCompany" uuid NOT NULL,
    "Title" character varying(100) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "CreationDatetime" timestamp without time zone NOT NULL,
    "IdEmployeeCreationAuditor" integer NOT NULL,
    "IdEmployeeRejectAuditor" integer,
    "IsSendToAudit" boolean,
    "SendToAuditDatetime" timestamp without time zone,
    "TechnicianComment" character varying(500),
    "IsRejected" boolean,
    "RejectedDatetime" timestamp without time zone,
    CONSTRAINT "PK_IdSupportTicketScheduleAudit" PRIMARY KEY ("IdSupportTicketScheduleAudit"),
    CONSTRAINT "FK_SupportTicketScheduleAudit_Company" FOREIGN KEY ("IdCompany") REFERENCES "Company" ("IdCompany"),
    CONSTRAINT "FK_SupportTicketScheduleAudit_Employee" FOREIGN KEY ("IdEmployeeCreationAuditor") REFERENCES "Employee" ("IdEmployee"),
    CONSTRAINT "FK_SupportTicketScheduleAudit_EmployeeAuditor" FOREIGN KEY ("IdEmployeeRejectAuditor") REFERENCES "Employee" ("IdEmployee"),
    CONSTRAINT "FK_SupportTicketScheduleAudit_SupportTicketSchedule" FOREIGN KEY ("IdSupportTicketSchedule") REFERENCES "SupportTicketSchedule" ("IdSchedule")
);


CREATE TABLE "SupportTicketScheduleTechnicianLog" (
    "IdSupportTicketScheduleTechnicianLog" uuid NOT NULL DEFAULT ((gen_random_uuid())),
    "IdSupportTicketSchedule" integer NOT NULL,
    "IdEmployee" integer NOT NULL,
    "Latitude" numeric(18,10) NOT NULL,
    "Longitude" numeric(18,10) NOT NULL,
    "IdTermTypeSupportTicketScheduleTechnicianLog" integer NOT NULL,
    "StartDateTime" timestamp without time zone NOT NULL,
    "EndDateTime" timestamp without time zone,
    "DurationTime" bigint,
    CONSTRAINT "PK_IdSupportTicketScheduleTechnicianLog" PRIMARY KEY ("IdSupportTicketScheduleTechnicianLog"),
    CONSTRAINT "FK_IdEmployee" FOREIGN KEY ("IdEmployee") REFERENCES "Employee" ("IdEmployee"),
    CONSTRAINT "FK_IdSupportTicketSchedule" FOREIGN KEY ("IdSupportTicketSchedule") REFERENCES "SupportTicketSchedule" ("IdSchedule"),
    CONSTRAINT "FK_IdTermTypeSupportTicketScheduleTechnicianLog" FOREIGN KEY ("IdTermTypeSupportTicketScheduleTechnicianLog") REFERENCES "Terms" ("IdTerms")
);


CREATE INDEX "IX_Address_IdCity" ON "Address" ("IdCity");


CREATE INDEX "IX_Address_IdNeighborhood" ON "Address" ("IdNeighborhood");


CREATE INDEX "IX_Address_IdTermSocioeconomic" ON "Address" ("IdTermSocioeconomic");


CREATE UNIQUE INDEX "UC_Address_Company_City" ON "Address" ("idCompany", "IdCity", "Address");


CREATE UNIQUE INDEX "UQ__AddressH__F1CFF37E029F4D38" ON "AddressHorizontalProperty" ("IdAddress");


CREATE INDEX "IX_BranchCompany_idCompany" ON "BranchCompany" ("idCompany");


CREATE INDEX "IX_BranchCompanyDocumentConsecutive_IdBranchCompany" ON "BranchCompanyDocumentConsecutive" ("IdBranchCompany");


CREATE INDEX "IX_BranchCompanyDocumentConsecutive_IdDocumentConsecutive" ON "BranchCompanyDocumentConsecutive" ("IdDocumentConsecutive");


CREATE INDEX "IX_BranchCompanyDocumentConsecutive_IdDocumentTemplate" ON "BranchCompanyDocumentConsecutive" ("IdDocumentTemplate");


CREATE INDEX "IX_CashRegister_IdOffice" ON "CashRegister" ("IdOffice");


CREATE INDEX "IX_CashRegister_IdTerminal" ON "CashRegister" ("IdTerminal");


CREATE UNIQUE INDEX "UQ__CashRegi__0F283CCF3080FFB8" ON "CashRegister" ("AddressMac");


CREATE UNIQUE INDEX "UQ__CashRegi__1EB4F817AA6968E1" ON "CashRegister" ("Token");


CREATE INDEX "IX_CashRegisterLog_IdCashRegister" ON "CashRegisterLog" ("IdCashRegister");


CREATE INDEX "IX_CashRegisterLog_IdEmployee" ON "CashRegisterLog" ("IdEmployee");


CREATE INDEX "IX_City_IdState" ON "City" ("IdState");


CREATE INDEX "IX_Company_IdCity" ON "Company" ("IdCity");


CREATE UNIQUE INDEX "UQ__Company__C7D1D6DAAFC20E16" ON "Company" ("Nit");


CREATE INDEX "IX_CompanyCustomTerm_IdCompany" ON "CompanyCustomTerm" ("IdCompany");


CREATE INDEX "IX_CompanyCustomTerm_IdCompanyCustomTermGroup" ON "CompanyCustomTerm" ("IdCompanyCustomTermGroup");


CREATE UNIQUE INDEX "UQ_IdCompanyCustomTermParent_IdCompanyCustomTermChild" ON "CompanyCustomTermChild" ("IdCompanyCustomTermParent", "IdCompanyCustomTermChild");


CREATE INDEX "IX_CompanyCustomTermGroup_IdCompany" ON "CompanyCustomTermGroup" ("IdCompany");


CREATE INDEX "IX_CompanyEntityCustomField_IdCompany" ON "CompanyEntityCustomField" ("IdCompany");


CREATE INDEX "IX_CompanyEntityCustomField_IdTermCustomField" ON "CompanyEntityCustomField" ("IdTermCustomField");


CREATE INDEX "IX_CompanyEntityCustomField_IdTermEntity" ON "CompanyEntityCustomField" ("IdTermEntity");


CREATE INDEX "IX_CompanyParameter_IdCompany" ON "CompanyParameter" ("IdCompany");


CREATE INDEX "IDX_Contract_by_IdCompany_Index" ON "Contract" ("IdCompany");


CREATE INDEX "IX_Contract_IdAddressFacturation" ON "Contract" ("IdAddressFacturation");


CREATE INDEX "IX_Contract_IdAddressInstalation" ON "Contract" ("IdAddressInstalation");


CREATE INDEX "IX_Contract_IdBranchCompany" ON "Contract" ("IdBranchCompany");


CREATE INDEX "IX_Contract_IdEmployeeLastChange" ON "Contract" ("IdEmployeeLastChange");


CREATE INDEX "IX_Contract_IdPerson" ON "Contract" ("IdPerson");


CREATE INDEX "IX_Contract_IdPlanService" ON "Contract" ("IdPlanService");


CREATE INDEX "IX_Contract_IdTermContractStatus" ON "Contract" ("IdTermContractStatus");


CREATE INDEX "IX_Contract_IdTermTicketAction" ON "Contract" ("IdTermTicketAction");


CREATE INDEX "IDX_ContractConnection_By_IdContract" ON "ContractConnection" ("IdContract");


CREATE INDEX "IX_ContractConnection_IdTermConnectionType" ON "ContractConnection" ("IdTermConnectionType");


CREATE INDEX "IX_ContractConnection_IdTermGenericService" ON "ContractConnection" ("IdTermGenericService");


CREATE UNIQUE INDEX "UQ_ContractConnection_ConnectionHash" ON "ContractConnection" ("ConnectionHash");


CREATE INDEX "IX_ContractConnectionHistory_IdContract" ON "ContractConnectionHistory" ("IdContract");


CREATE INDEX "IX_ContractConnectionHistory_IdTermConnectionType" ON "ContractConnectionHistory" ("IdTermConnectionType");


CREATE INDEX "IX_ContractConnectionHistory_IdTermGenericService" ON "ContractConnectionHistory" ("IdTermGenericService");


CREATE INDEX "IX_ContractCustomField_IdCompanyEntityCustomField" ON "ContractCustomField" ("IdCompanyEntityCustomField");


CREATE INDEX "IX_DocumentConsecutive_IdCompany" ON "DocumentConsecutive" ("IdCompany");


CREATE INDEX "IX_DocumentConsecutive_IdDocumentTemplate" ON "DocumentConsecutive" ("IdDocumentTemplate");


CREATE INDEX "IX_DocumentConsecutive_IdTermDocumentConsecutive" ON "DocumentConsecutive" ("IdTermDocumentConsecutive");


CREATE INDEX "IX_DocumentTemplate_IdTermDocument" ON "DocumentTemplate" ("IdTermDocument");


CREATE INDEX "IX_Employee_IdCompany" ON "Employee" ("IdCompany");


CREATE INDEX "IX_Employee_IdPerson" ON "Employee" ("IdPerson");


CREATE INDEX "IX_Employee_IdTermJobPosition" ON "Employee" ("IdTermJobPosition");


CREATE INDEX "IX_Expense_IdCashRegisterLog" ON "Expense" ("IdCashRegisterLog");


CREATE INDEX "IX_Expense_IdCompanyCustomTermExpenseType" ON "Expense" ("IdCompanyCustomTermExpenseType");


CREATE INDEX "IX_Expense_IdTermStatusExpense" ON "Expense" ("IdTermStatusExpense");


CREATE INDEX "IX_GenericService_idTermGenericService" ON "GenericService" ("idTermGenericService");


CREATE INDEX "IX_HorizontalProperty_IdAddress" ON "HorizontalProperty" ("IdAddress");


CREATE INDEX "IDX_Invoice_By_IdCompany_IdContract" ON "Invoice" ("IdCompany", "IdContract");


CREATE INDEX "IDX_Invoice_by_IdCompany_Index" ON "Invoice" ("IdCompany");


CREATE INDEX "IX_Invoice_idBranchCompany" ON "Invoice" ("idBranchCompany");


CREATE INDEX "IX_Invoice_IdContract" ON "Invoice" ("IdContract");


CREATE INDEX "IDX_InvoiceDetail_By_Invoice" ON "InvoiceDetail" ("IdInvoice");


CREATE INDEX "IX_InvoiceDetail_IdItem" ON "InvoiceDetail" ("IdItem");


CREATE INDEX "IDX_InvoiceRecurrent_IdContract" ON "InvoiceRecurrent" ("IdContract");


CREATE INDEX "IX_InvoiceRecurrent_IdItemService" ON "InvoiceRecurrent" ("IdItemService");


CREATE INDEX "IX_InvoiceRecurrentDetail_IdInvoiceDetail" ON "InvoiceRecurrentDetail" ("IdInvoiceDetail");


CREATE UNIQUE INDEX "UQ__InvoiceR__2AC4ACAAB1643FAA" ON "InvoiceRecurrentDetail" ("IdInvoiceRecurrent");


CREATE INDEX "IX_Item_IdCompany" ON "Item" ("IdCompany");


CREATE INDEX "IX_Item_IdTermTypeItem" ON "Item" ("IdTermTypeItem");


CREATE INDEX "IX_Neighborhood_IdCity" ON "Neighborhood" ("IdCity");


CREATE INDEX "IX_Neighborhood_IdCompany" ON "Neighborhood" ("IdCompany");


CREATE INDEX "IX_Neighborhood_IdZone" ON "Neighborhood" ("IdZone");


CREATE INDEX "IX_NeighborhoodPlanService_IdNeighborhood" ON "NeighborhoodPlanService" ("IdNeighborhood");


CREATE INDEX "IX_NeighborhoodPlanService_IdPlanService" ON "NeighborhoodPlanService" ("IdPlanService");


CREATE INDEX "IX_Office_IdBranchCompany" ON "Office" ("IdBranchCompany");


CREATE INDEX "IX_OnlinePay_IdCompany" ON "OnlinePay" ("IdCompany");


CREATE INDEX "IX_OnlinePay_IdContract" ON "OnlinePay" ("IdContract");


CREATE INDEX "IX_OnlinePay_IdTermOnlinePayStatus" ON "OnlinePay" ("IdTermOnlinePayStatus");


CREATE INDEX "IX_OnlinePay_idThirdPartyApplication" ON "OnlinePay" ("idThirdPartyApplication");


CREATE INDEX "IX_OnlinePayLog_IdOnlinePay" ON "OnlinePayLog" ("IdOnlinePay");


CREATE INDEX "IX_OnlinePayLog_IdTermOnlinePayStatus" ON "OnlinePayLog" ("IdTermOnlinePayStatus");


CREATE INDEX "IX_OnuStock_Status" ON "OnuStock" ("Status");


CREATE INDEX "IX_Person_Gender" ON "Person" ("Gender");


CREATE INDEX "IX_Person_IdCity" ON "Person" ("IdCity");


CREATE INDEX "IX_Person_Rh" ON "Person" ("Rh");


CREATE INDEX "IX_Person_TypeIdentification" ON "Person" ("TypeIdentification");


CREATE INDEX "IX_Person_TypePerson" ON "Person" ("TypePerson");


CREATE UNIQUE INDEX "UQ_Company_TypeIdentification_Nuip" ON "Person" ("IdCompany", "TypeIdentification", "Nuip");


CREATE INDEX "IX_PersonEmail_IdTermTypeEmail" ON "PersonEmail" ("IdTermTypeEmail");


CREATE UNIQUE INDEX "UQ_PersonEmail_IdPerson_Email" ON "PersonEmail" ("IdPerson", "Email");


CREATE INDEX "IDX_PersonPhoneNumber_by_IdPerson" ON "PersonPhoneNumber" ("IdPerson");


CREATE INDEX "IX_PersonPhoneNumber_IdCity" ON "PersonPhoneNumber" ("IdCity");


CREATE INDEX "IX_PersonPhoneNumber_IdTermTypePhonNumber" ON "PersonPhoneNumber" ("IdTermTypePhonNumber");


CREATE UNIQUE INDEX "UQ_PersonPhoneNumber_IdPerson_PhoneNumber" ON "PersonPhoneNumber" ("IdPerson", "PhoneNumber");


CREATE INDEX "IX_PlanService_IdCompany" ON "PlanService" ("IdCompany");


CREATE INDEX "IX_PlanServiceDetail_IdItemService" ON "PlanServiceDetail" ("IdItemService");


CREATE INDEX "IX_PlanServiceDetail_IdPlanService" ON "PlanServiceDetail" ("IdPlanService");


CREATE INDEX "IX_Report_IdTermReportCategory" ON "Report" ("IdTermReportCategory");


CREATE INDEX "IX_State_IdCountry" ON "State" ("IdCountry");


CREATE INDEX "IDX_SupporTicket_by_IdCompany_IdContract" ON "SupportTicket" ("IdCompany", "IdContract");


CREATE INDEX "IX_SupportTicket_idBranchCompany" ON "SupportTicket" ("idBranchCompany");


CREATE INDEX "IX_SupportTicket_IdContract" ON "SupportTicket" ("IdContract");


CREATE INDEX "IX_SupportTicket_IdEmployee" ON "SupportTicket" ("IdEmployee");


CREATE INDEX "IX_SupportTicket_IdItemTypeSupportTicket" ON "SupportTicket" ("IdItemTypeSupportTicket");


CREATE INDEX "IX_SupportTicket_IdTermTicketScheduleType" ON "SupportTicket" ("IdTermTicketScheduleType");


CREATE INDEX "IDX_SupporTicketSchedule_IdSupportTicket" ON "SupportTicketSchedule" ("IdSupportTicket");


CREATE INDEX "IX_SupportTicketSchedule_IdEmployee" ON "SupportTicketSchedule" ("IdEmployee");


CREATE INDEX "IX_SupportTicketSchedule_IdTermTicketScheduleType" ON "SupportTicketSchedule" ("IdTermTicketScheduleType");


CREATE INDEX "IX_SupportTicketSchedule_IdTermTicketScheduleTypeReason" ON "SupportTicketSchedule" ("IdTermTicketScheduleTypeReason");


CREATE INDEX "IX_SupportTicketScheduleAudit_IdCompany" ON "SupportTicketScheduleAudit" ("IdCompany");


CREATE INDEX "IX_SupportTicketScheduleAudit_IdEmployeeCreationAuditor" ON "SupportTicketScheduleAudit" ("IdEmployeeCreationAuditor");


CREATE INDEX "IX_SupportTicketScheduleAudit_IdEmployeeRejectAuditor" ON "SupportTicketScheduleAudit" ("IdEmployeeRejectAuditor");


CREATE INDEX "IX_SupportTicketScheduleAudit_IdSupportTicketSchedule" ON "SupportTicketScheduleAudit" ("IdSupportTicketSchedule");


CREATE INDEX "IX_SupportTicketScheduleTechnicianLog_IdEmployee" ON "SupportTicketScheduleTechnicianLog" ("IdEmployee");


CREATE INDEX "IX_SupportTicketScheduleTechnicianLog_IdTermTypeSupportTicketS~" ON "SupportTicketScheduleTechnicianLog" ("IdTermTypeSupportTicketScheduleTechnicianLog");


CREATE UNIQUE INDEX "UQ_SupportTicketScheduleTechnicianLog_IdSupportTicketSchedule_IdTermTypeSupportTicketScheduleTechnicianLog" ON "SupportTicketScheduleTechnicianLog" ("IdSupportTicketSchedule", "IdTermTypeSupportTicketScheduleTechnicianLog");


CREATE UNIQUE INDEX "UQ__Terminal__0F283CCFC9B8AE0B" ON "Terminal" ("AddressMac");


CREATE UNIQUE INDEX "UQ__Terminal__1EB4F81750E44F18" ON "Terminal" ("Token");


CREATE UNIQUE INDEX "UQ__Terminal__2500E15C91054E54" ON "Terminal" ("HostName");


CREATE INDEX "IX_Terms_IdTermsGroup" ON "Terms" ("IdTermsGroup");


CREATE INDEX "IX_ThirdPartyApplication_IdTermThirdPartyApplicationType" ON "ThirdPartyApplication" ("IdTermThirdPartyApplicationType");


CREATE INDEX "IX_ThirdPartyApplicationCompanyParameter_idCompany" ON "ThirdPartyApplicationCompanyParameter" ("idCompany");


CREATE INDEX "IX_ThirdPartyApplicationCompanyParameter_idThirdPartyApplicati~" ON "ThirdPartyApplicationCompanyParameter" ("idThirdPartyApplication");


CREATE INDEX "IX_TicketType_idTermTicketAction" ON "TicketType" ("idTermTicketAction");


CREATE INDEX "IDX_Voucher_By_CashRegisterLog>" ON "Voucher" ("IdCashRegisterLog");


CREATE INDEX "IDX_Voucher_by_IdCompany_Index" ON "Voucher" ("IdCompany");


CREATE INDEX "IX_Voucher_idBranchCompany" ON "Voucher" ("idBranchCompany");


CREATE INDEX "IX_Voucher_IdContract" ON "Voucher" ("IdContract");


CREATE INDEX "IX_Voucher_IdTermDocumentType" ON "Voucher" ("IdTermDocumentType");


CREATE INDEX "IX_Voucher_IdTermVoucherStatus" ON "Voucher" ("IdTermVoucherStatus");


CREATE UNIQUE INDEX "UQ_Voucher_IdCompany_Prefix_Consecutive_IdTermDocumentType" ON "Voucher" ("IdCompany", prefix, "Consecutive", "IdTermDocumentType");


CREATE INDEX "IDX_VoucherDetail_By_Voucher" ON "VoucherDetail" ("IdVoucher");


CREATE INDEX "IX_VoucherDetail_IdInvoiceDetail" ON "VoucherDetail" ("IdInvoiceDetail");


CREATE INDEX "IDX_VoucherPaymentMethods_by_IdVoucher" ON "VoucherPaymentMethods" ("IdVoucher");


CREATE INDEX "IX_VoucherPaymentMethods_IdTermBank" ON "VoucherPaymentMethods" ("IdTermBank");


CREATE INDEX "IX_VoucherPaymentMethods_IdTermFranchise" ON "VoucherPaymentMethods" ("IdTermFranchise");


CREATE INDEX "IX_VoucherPaymentMethods_IdTermTypeCard" ON "VoucherPaymentMethods" ("IdTermTypeCard");


CREATE INDEX "IX_VoucherPaymentMethods_IdTermTypePaymentMethod" ON "VoucherPaymentMethods" ("IdTermTypePaymentMethod");


CREATE INDEX "IX_Zone_IdCompany" ON "Zone" ("IdCompany");


CREATE INDEX "IX_ZonePlanService_IdPlanService" ON "ZonePlanService" ("IdPlanService");


CREATE INDEX "IX_ZonePlanService_IdZone" ON "ZonePlanService" ("IdZone");


